name: go test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.13.1'
      - name: Cache go modules
        uses: actions/cache@v1
        env:
          cache-name: cache-go-modules
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: go build discord client
        run: go build cmd/discord_client/main.go
      - name: go test
        run: go test -cover ./...